### ISSUE TITLE
problem with twogtp

### ISSUE THREAD

**Issue by gms2009** [Remi-Coulom/gogui#12]
on ubuntu 18.04
gogui running ok
but

BLACK="gnugo --mode gtp"
WHITE="gnugo --mode gtp --level 5"
gogui -program "gogui-twogtp -black \"$BLACK\" -white \"$WHITE\""

or

BLACK="gnugo --mode gtp"
WHITE="gnugo --mode gtp --level 5"
TWOGTP="gogui-twogtp -black \"$BLACK\" -white \"$WHITE\" -games 100 \
  -size 9 -alternate -sgffile gnugo5"
gogui -size 9 -program "$TWOGTP" -computer-both -auto

always got:
GoGui version: 1.5.1
Java version: OpenJDK Runtime Environment 11.0.3
Operating system: Linux

java.lang.NullPointerException
	at net.sf.gogui.gogui.GoGui.attachProgram(GoGui.java:2866)
	at net.sf.gogui.gogui.GoGui.initialize(GoGui.java:3845)
	at net.sf.gogui.gogui.GoGui.access$500(GoGui.java:140)
	at net.sf.gogui.gogui.GoGui$5.run(GoGui.java:324)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Remi-Coulom** [comment]
Thanks for reporting this problem. I could replicate it. We will fix it.
