### ISSUE TITLE
run on windows 10 report java error

### ISSUE THREAD

**Issue by l1t1** [Remi-Coulom/gogui#15]
i have set the java env, but gogui cannot run yet
```
E:\leela\katago131>set path=E:\Actian\Director\jre\bin;%path%

E:\leela\katago131>java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

E:\leela\katago131>set JAVA_HOME=E:\Actian\Director\jre

E:\leela\katago131>set CLASSPATH=E:\Actian\Director\jre\lib\rt.jar

E:\leela\katago131>e:\leela\gogui151\gogui-twogtp
This application requires a Java Runtime Environment 1.5.0
```
if i run gogui 1.4.9
reports
```
E:\leela\katago131>e:\leela\gogui149\gogui-twogtp
Launch4j: This application requires a Java Runtime Environment 1.5.0
```

**Comment by Remi-Coulom** [comment]
I am not sure the exe takes JAVA_HOME into consideration. Do you have an old JDK anywhere on your machine?

**Comment by l1t1** [comment]
in my another pc runing windows7, java  is not in path either, but 1.4.9 works, 1.5.1 reports error
```
D:\tool\go_gui>gogui-twogtp -version
gogui-twogtp 1.4.9
D:\gogui151>gogui-twogtp -version
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/sf/gogui/tools/twogtp/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: net.sf.gogui.tools.twogtp.Main. Program will exit.
```

**Comment by Remi-Coulom** [comment]
I have not time to look into the details of this problem. My suggestion would be to run the jar directly instead of using Launch4j's wrapper.

**Comment by l1t1** [comment]
what is the command of jar file?

**Comment by Remi-Coulom** [comment]
The jar file is not distributed in the Windows installer. You'd have to compile gogui from source.

Note that gogui-twogtp.exe works on my Windows 10 machine. I don't know what's wrong with your configuration, but there should be a way to make the exe work.

**Comment by Remi-Coulom** [comment]
I am closing this, as I will package the next version differently. If you still have a problem with the upcoming version 1.5.2, then please open another issue.
