### ISSUE TITLE
com.apple.eawt classes not found

### ISSUE THREAD

**Issue by zliu1022** [Remi-Coulom/gogui#18]
I use macOS 10.15 with 
- openjdk 12.0.1 2019-04-16
- OpenJDK Runtime Environment (build 12.0.1+12)
- OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

When I run ` java -jar gogui.jar`, the following message run out.
Anyone can help me ?
Thanks

BasicQuaquaLookAndFeel controlBG:javax.swing.plaf.ColorUIResource[r=238,g=238,b=238]
Could not register handler for Mac events. (com.apple.eawt classes not found)
java.lang.NoSuchMethodError:
java.awt.Container.getPeer()Ljava/awt/peer/ComponentPeer;
java.lang.NoSuchMethodError: java.awt.Container.getPeer()Ljava/awt/peer/ComponentPeer;
	at ch.randelshofer.quaqua.Quaqua14RootPaneUI.updateWindowModified(Quaqua14RootPaneUI.java:324)
	at ch.randelshofer.quaqua.Quaqua14RootPaneUI.propertyChange(Quaqua14RootPaneUI.java:563)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8728)
	at java.desktop/javax.swing.JComponent.putClientProperty(JComponent.java:4117)
	at net.sf.gogui.gogui.GoGui.updateViews(GoGui.java:4394)
	at net.sf.gogui.gogui.GoGui.updateViews(GoGui.java:4378)
	at net.sf.gogui.gogui.GoGui.initialize(GoGui.java:3471)
	at net.sf.gogui.gogui.GoGui.access$400(GoGui.java:137)
	at net.sf.gogui.gogui.GoGui$5.run(GoGui.java:312)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Remi-Coulom** [comment]
I tested on a mac, and the new version works. I will package a new release very soon.
