### ISSUE TITLE
Error when launching gui

### ISSUE THREAD

**Issue by OmnipotentEntity** [Remi-Coulom/gogui#36]
When I attempt to launch gogui from the command line I get the following backtrace:

```
java.lang.NullPointerException:
Cannot invoke "java.net.URL.toString()" because "url" is null
java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because "url" is null
        at java.desktop/sun.awt.SunToolkit.getImageFromHash(SunToolkit.java:698)
        at java.desktop/sun.awt.SunToolkit.getImage(SunToolkit.java:734)
        at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:213)
        at net.sf.gogui.gui.GuiUtil.getUnsizedIcon(GuiUtil.java:190)
        at net.sf.gogui.gui.GameInfoPanel.<init>(GameInfoPanel.java:52)
        at net.sf.gogui.gogui.GoGui.<init>(GoGui.java:210)
        at net.sf.gogui.gogui.Main$2.run(Main.java:129)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

This is a strange error, because referencing [`GameInfoPanel.<init>`](https://github.com/Remi-Coulom/gogui/blob/master/src/net/sf/gogui/gui/GameInfoPanel.java#L52) and [`GuiUtil.getUnsizedIcon`](https://github.com/Remi-Coulom/gogui/blob/master/src/net/sf/gogui/gui/GuiUtil.java#L190), the URL of the icon is being set.

I traced it back to the icon in question, `gogui-white-32x32`, simply not being available inside of the jar file that I built, and it's also not in the project tree either.  It is, however, in the distributed binaries.  So there may be some icons on your computer that were never committed on accident.

**Comment by OmnipotentEntity** [comment]
A full list of such icons

```
document-open-16x16.png
document-open-24x24.png
document-open-32x32.png
document-open-48x48.png
document-open-64x64.png
document-save-16x16.png
document-save-24x24.png
document-save-32x32.png
document-save-48x48.png
document-save-64x64.png
gogui-16x16.png
gogui-24x24.png
gogui-32x32.png
gogui-48x48.png
gogui-64x64.png
gogui-black-16x16.png
gogui-black-24x24.png
gogui-black-32x32.png
gogui-black-48x48.png
gogui-black-64x64.png
gogui-black-8x8.png
gogui-down-16x16.png
gogui-down-24x24.png
gogui-down-32x32.png
gogui-down-48x48.png
gogui-down-64x64.png
gogui-first-16x16.png
gogui-first-24x24.png
gogui-first-32x32.png
gogui-first-48x48.png
gogui-first-64x64.png
gogui-last-16x16.png
gogui-last-24x24.png
gogui-last-32x32.png
gogui-last-48x48.png
gogui-last-64x64.png
gogui-newgame-16x16.png
gogui-newgame-24x24.png
gogui-newgame-32x32.png
gogui-newgame-48x48.png
gogui-newgame-64x64.png
gogui-next-10-16x16.png
gogui-next-10-24x24.png
gogui-next-10-32x32.png
gogui-next-10-48x48.png
gogui-next-10-64x64.png
gogui-next-16x16.png
gogui-next-24x24.png
gogui-next-32x32.png
gogui-next-48x48.png
gogui-next-64x64.png
gogui-pass-16x16.png
gogui-pass-24x24.png
gogui-pass-32x32.png
gogui-pass-48x48.png
gogui-pass-64x64.png
gogui-play-16x16.png
gogui-play-24x24.png
gogui-play-32x32.png
gogui-play-48x48.png
gogui-play-64x64.png
gogui-previous-10-16x16.png
gogui-previous-10-24x24.png
gogui-previous-10-32x32.png
gogui-previous-10-48x48.png
gogui-previous-10-64x64.png
gogui-previous-16x16.png
gogui-previous-24x24.png
gogui-previous-32x32.png
gogui-previous-48x48.png
gogui-previous-64x64.png
gogui-setup-16x16.png
gogui-setup-24x24.png
gogui-setup-32x32.png
gogui-setup-48x48.png
gogui-setup-64x64.png
gogui-setup-8x8.png
gogui-setup-black-16x16.png
gogui-setup-black-24x24.png
gogui-setup-black-32x32.png
gogui-setup-black-48x48.png
gogui-setup-black-64x64.png
gogui-setup-white-16x16.png
gogui-setup-white-24x24.png
gogui-setup-white-32x32.png
gogui-setup-white-48x48.png
gogui-setup-white-64x64.png
gogui-up-16x16.png
gogui-up-24x24.png
gogui-up-32x32.png
gogui-up-48x48.png
gogui-up-64x64.png
gogui-white-16x16.png
gogui-white-24x24.png
gogui-white-32x32.png
gogui-white-48x48.png
gogui-white-64x64.png
gogui-white-8x8.png
go-home-16x16.png
go-home-24x24.png
go-home-32x32.png
go-home-48x48.png
go-home-64x64.png
go-next-16x16.png
go-next-24x24.png
go-next-32x32.png
go-next-48x48.png
go-next-64x64.png
go-previous-16x16.png
go-previous-24x24.png
go-previous-32x32.png
go-previous-48x48.png
go-previous-64x64.png
```

**Comment by OmnipotentEntity** [comment]
Actually, looking a little bit closer, it seems like these ought to have been generated by the svg files located in src/net/sf/gogui/images, I am currently investigating why these were not generated by ant, sorry about the additional noise.

**Comment by Remi-Coulom** [comment]
instructions to build in ubuntu-like systems are in that file:

https://github.com/Remi-Coulom/gogui/blob/master/ubuntu_setup.sh

You have to run ``svg.sh`` in the ``src/net/sf/gogui/images`` directory. I don't know how to tell ant to do it automatically. If your system is not ubuntu, you may have to adjust what svg.sh does. Or you can simply extract all pictures from the jar.

**Comment by OmnipotentEntity** [comment]
Thanks!  Weird that I overlooked this.

**Comment by Remi-Coulom** [comment]
I added build instructions to README.md. This should makes this information easier to find.
